In [ ]:
import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

print("Q (Orthogonal matrix):")
print(Q)
print("\nR (Upper triangular matrix):")
print(R)



Q (Orthogonal matrix):
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]

R (Upper triangular matrix):
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [ ]:
import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, S, Vt = np.linalg.svd(A)

print("U (Left singular vectors):")
print(U)
print("\nS (Singular values):")
print(np.diag(S))
print("\nVt (Right singular vectors):")
print(Vt)



U (Left singular vectors):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

S (Singular values):
[[9.52551809 0.        ]
 [0.         0.51430058]]

Vt (Right singular vectors):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
import numpy as np

# Define data matrix
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Center the data
mean = np.mean(data, axis=0)
centered_data = data - mean

# Perform SVD
U, S, Vt = np.linalg.svd(centered_data)

# Calculate principal components
PCs = Vt.T

print("Principal Components:")
print(PCs)


Principal Components:
[[ 0.57735027  0.          0.81649658]
 [ 0.57735027 -0.70710678 -0.40824829]
 [ 0.57735027  0.70710678 -0.40824829]]
